# Generated by Django 3.2.5 on 2021-11-13 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_ID', models.TextField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.TextField()),
                ('date_created', models.DateField(default=datetime.date.today)),
                ('image', models.URLField()),
                ('current_role', models.TextField()),
                ('tech_industry', models.BooleanField()),
                ('programs_complete', models.CharField(choices=[('1 Day Tech Workshop', '1 Day Tech Workshop'), ('1 Week Flash Program', '1 Week Flash Program'), ('She Codes Plus Program', 'She Codes Plus Program')], max_length=200)),
                ('programs_interested', models.CharField(choices=[('1 Day Tech Workshop', '1 Day Tech Workshop'), ('1 Week Flash Program', '1 Week Flash Program'), ('She Codes Plus Program', 'She Codes Plus Program')], max_length=200)),
                ('location', models.CharField(choices=[('Brisbane', 'Brisbane'), ('Perth', 'Perth'), ('Port Hedland', 'Port Hedland')], max_length=200)),
                ('mentoring', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('No, But Intested', 'No, But Interested')], max_length=200)),
                ('partner_hire', models.CharField(choices=[('BHP', 'BHP'), ('Bunnings', 'Bunnings'), ('VGW', 'VGW')], max_length=200)),
                ('post_study', models.BooleanField()),
            ],
        ),
    ]
