# Generated by Django 3.2.5 on 2021-11-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coders',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='coders',
            name='mentoring',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='coders',
            name='partner_hire',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='coders',
            name='programs_complete',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='coders',
            name='programs_interested',
            field=models.CharField(max_length=200),
        ),
    ]
