# Generated by Django 3.2.5 on 2021-11-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coders', '0003_auto_20211120_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coders',
            name='partner_hire',
            field=models.BooleanField(),
        ),
    ]
