# Generated by Django 3.2.5 on 2021-11-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='test',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
